### PR TITLE
Work around lack of connect timeout

### LINKED ISSUE #32: Timeout not working
I've discovered the timeout mechanism isn't working. In some tests, the reactor will run forever, but most of the time the test will take about ~1 minute.  The timeout value seems to be ignored.  I've stepped through with xdebug, but it gets lost and i can't seem to identify the issue. Example:

```
$promise = \Amp\Dns\resolve('www.google.ca', ['timeout' => 100, 'server' => 'tcp://8.8.8.0:53', 
  'types' => Record::A, 'cache' => false ]);

try {
    $result = \Amp\wait($promise);
    $this->fail("Resolve did not timeout when expected {$result}");
} catch (\Exception $e) {
    $this->assertInstanceOf(\Exception::class, $e);
}
```

I've tried with and without ev extension. I've tried with regular IP, udp scheme, smaller/larger values, cache on/off. 

This is with php version 5.5.30. and amphp/dns 0.8.10

Any ideas or recommendations to get this working?

### PR DESCRIPTION
**Pull request by chrisleavoy**
Fixes #32

### CODE REVIEW

**Comment by bwoebi** [comment]
I rather meant to try `STREAM_CLIENT_ASYNC_CONNECT`. Your patch is doing a blocking connect.
Currently working on it, I'll push shortly.

**Comment by chrisleavoy** [comment]
Thanks! I did experiment with STREAM_CLIENT_ASYNC_CONNECT after seeing it in amphp/socket, but it changed too much existing behavior for me to feel comfortable screwing with it. :)

**Comment by bwoebi** [comment]
Not much existing behavior is changed, see ba6016dd0a2a79e2eed8b2392ae3002d49120aaa

But thanks for finding our mistake… blocking connects are always bad!

**Comment by bwoebi** [comment]
Just as a note: when you do an async connect, you just have to wait for writability (this means: connected and buffers not full).

**Pull request closed without merging**
