### PR TITLE
Fix an infinite loop when all 65536 requests are done

### PR DESCRIPTION
**Pull request by bwoebi**
Also use a CSPRNG for generating random numbers (fallback to paragonie/random_compat for PHP 5)

### CODE REVIEW

**Comment by kelunik** [comment]
That's not a robust solution. I think we should just use a second port when there's too high concurrency.

**Comment by bwoebi** [comment]
Good point … totally not thought about opening a separate UDP connection…

**Comment by bwoebi** [comment]
This will though require a bit more of a refactor … delaying then to sometime else.

**Comment by kelunik** [comment]
The possible infinite loop is fixed in the Amp v2 version.

**Pull request closed without merging**
