### PR TITLE
Cache composer dependecies for faster builds

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by bwoebi** [comment]
Could you please explain how this takes effect? Comparing build time of the PR on travis, I see no difference to older builds?

**Comment by kelunik** [comment]
Because the cache is not yet there, it's the first commit.

**Comment by kelunik** [comment]
Thanks!

**Comment by staabm** [comment]
@bwoebi this PR does not yet benefit from the build cache, only commits after this one will.

the benefit is, that composer packages wont get downloaded over http but instead will be re-used from previous builds.

**Comment by kelunik** [comment]
This commit won't anyway, because it's a separate branch and has it's own cache.

**Pull request merged**
